print("hello world!!")
print('When your were here?')
print("Want to choose")
print("hello world!!")
print('When your were here?')
print("Want to choose")
print("hello world!!")
print('When your were here?')
print("Want to choose")